### ISSUE TITLE
How about https://github.com/presslabs/mysql-operator

### ISSUE THREAD

**Issue by andyli029** [cndoit18/cndoit18#1]
How about presslabs/mysql-operator ？

**Comment by cndoit18** [comment]
Hi, I see you are Chinese, so I will communicate with you directly in Chinese.

它还不错，之前有几个问题，我已经修复它了。社区的更新速度很慢，所以我最近正在投入精力去完善它，但是因为需求不太明确，所以现在进度也比较缓慢

目前我们也没有把握它能支撑多大的量级，如果您有这方面的数据，欢迎一起沟通

**Comment by andyli029** [comment]
你好，社区的更新速度是很慢，比较缓慢的推进
有邮箱嘛，联系起来方便？

**Comment by cndoit18** [comment]
> 你好，社区的更新速度是很慢，而且很多问题没有回音。
> 有邮箱嘛，联系起来方便？

你指的是社区的吗？还是我的？你可以使用slack 在渠道#kubernetes

**Comment by andyli029** [comment]
github没看到，你的邮箱？方便提供下不

**Comment by cndoit18** [comment]
社区的话，好像是没有邮箱. 你只能通过slack上去咨询一下

我的刚更新到github上了

主页应该有显示

**Comment by andyli029** [comment]
> 社区的话，好像是没有邮箱. 你只能通过slack上去咨询一下
> 
> 我的刚更新到github上了

Good Job
